export enum EnvConfigEnum {
  APP_AWS_REGION = 'APP_AWS_REGION',
  APP_AWS_ACCESS_KEY_ID = 'APP_AWS_ACCESS_KEY_ID',
  APP_AWS_SECRET_ACCESS_KEY = 'APP_AWS_SECRET_ACCESS_KEY',
  APP_AWS_BUCKET = 'APP_AWS_BUCKET',
  PORT = 'PORT',
  TOKEN_SECRET = 'TOKEN_SECRET',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  CONNECTION_STRING = 'CONNECTION_STRING',
  TOKEN_EXPIRATION_TIME = 'TOKEN_EXPIRATION_TIME',
  REFRESH_TOKEN_EXPIRATION_TIME = 'REFRESH_TOKEN_EXPIRATION_TIME',
}
