export const envConfiguration = {
  PORT: 'PORT',
  TOKEN_EXPIRATION_TIME: 'TOKEN_EXPIRATION_TIME',
  TOKEN_SECRET: 'TOKEN_SECRET',
  CONNECTION_STRING: 'CONNECTION_STRING',
  REFRESH_TOKEN_EXPIRATION_TIME: 'REFRESH_TOKEN_EXPIRATION_TIME',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  RESET_PASSWORD_TOKEN_EXPIRATION_TIME: 'RESET_PASSWORD_TOKEN_EXPIRATION_TIME',
  SECRET_KEY: 'SECRET_KEY',
};
